### PR TITLE
made the code more 𝓯𝓻𝓮𝓪𝓴𝔂

### PR DESCRIPTION
**Pull request by ghost**
please merge asap

### CODE REVIEW

**Comment by ghost** [comment]
LGTM

**Review by ar1ja — CHANGES_REQUESTED** [review]
u need help

**Comment by jjj333-p** [comment]
imagine if node actually could run this

**Comment by ar1ja** [comment]
> imagine if node actually could run this

pre-processor :trollface:

**Comment by kernaltrap8** [comment]
𝓱𝓮𝓵𝓵𝓸 𝓬𝓲𝓷𝓷𝔂

**Comment by kernaltrap8** [comment]
:doomguy:

**Comment by array-in-a-matrix** [comment]
this needs merging ASAP :shipit:

**Comment by ghost** [comment]
Wowzers!! You are such a good and talented programmer, @pixieclaws! Please merge this ASAP!!! @jjj333-p

**Comment by Hydrogen8** [comment]
looks bad to me

**Comment by jjj333-p** [comment]
So true bestie

**Comment by Hydrogen8** [comment]
this should have been merged and then reverted simply because it's
funny

**Comment by jjj333-p** [comment]
i dont know shithub enough to do that without fucking myself in the asshole

**Comment by Hydrogen8** [comment]
you don't need to know github you just need to know git

you just commit the changes and then revert the commits and commit that
new state

**Comment by ghost** [comment]
LGTM

**Pull request closed without merging**
